### ISSUE TITLE
Describe decentralization and federation debate, inc. blockchain critique

### ISSUE THREAD

**Issue by gandhiano** [gandhiano/technology-degrowth#6]
The ongoing debate on decentralization and federation of data, platforms and infrastructure is one with an immense bridging potential between the movements. The ideas of federation, as well as those conveyed in some of the blockchain critiques, are particularly interesting for a convergence of discourses and praxis (q4).

Here are a few links I have been reading for this purpose:
- https://blog.p2pfoundation.net/socialisme-ou-barbarie-castoriadis-project-individual-collective-autonomy-collaborative-commons/2016/05/20
- https://blog.p2pfoundation.net/can-cryptocurrency-blockchain-technology-play-role-building-social-solidarity-finance/2016/04/01
- http://wiki.p2pfoundation.net/Blockchain#The_key_questions_about_the_blockchain
- https://english.lasindias.com/blockchain-is-a-threat-to-the-distributed-future-of-the-internet
- http://www.coindesk.com/bitcoin-miners-ethereum/

**Comment by almereyda** [comment]
Instead of describing these issues, it may only be possible to sketch them in such a paper.

Fortunately there are more sources than the P2P Foundation to this subject:
- http://brewster.kahle.org/2015/08/11/locking-the-web-open-a-call-for-a-distributed-web-2/
  - https://ipfs.io/ipfs/QmavE42xtK1VovJFVTVkCR5Jdf761QWtxmvak9Zx718TVr/2015/04/22/locking-the-web-open-a-call-for-a-distributed-web/index.html
  - http://blog.dshr.org/2016/04/brewster-kahles-distributed-web-proposal.html
- https://medium.com/matter/the-web-we-have-to-save-2eb1fe15a426
- http://networkcultures.org/unlikeus/resources/articles/what-is-a-federated-network/

Then criticising the distributed ledgers only works if we agree on proper terms do define the actual problem/question to be solved.
- http://graydon2.dreamwidth.org/201698.html
